AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 2048
    Timeout: 30

Resources:
  layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sparticuz-chromium
      ContentUri: code/
      CompatibleRuntimes:
        - nodejs16.x
        - nodejs18.x
        - nodejs20.x
        - nodejs22.x

  node16:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref layer
      Handler: handlers/index.handler
      Runtime: nodejs16.x
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXRayDaemonWriteAccess
      Tracing: Active
  node18:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref layer
      Handler: handlers/index.handler
      Runtime: nodejs18.x
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXRayDaemonWriteAccess
      Tracing: Active
  node20:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref layer
      Handler: handlers/index.handler
      Runtime: nodejs20.x
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXRayDaemonWriteAccess
      Tracing: Active
  node22:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref layer
      Handler: handlers/index.handler
      Runtime: nodejs22.x
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXRayDaemonWriteAccess
      Tracing: Active
